### PR TITLE
Add new args to admin.users.list and update web API response types

### PR DESCRIPTION
**Pull request by seratch**
###  Summary

This pull request adds two newly added options to https://api.slack.com/methods/admin.users.list

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by seratch** [comment]
@filmaj Do you have ETA for https://github.com/slackapi/node-slack-sdk/pull/1673? If it can take long (that's totally fine!), we may want to cherry-pick this change and cut a new release in 6.x series.

**Comment by filmaj** [comment]
@seratch yes I believe it will take longer. I can merge this into a 6.x maintenance branch and release.

**Comment by filmaj** [comment]
@seratch I have created a `web-api-6.x` branch based off the branch that we released 6.9.1. Can you change the target of this PR to that branch, please?

**Comment by filmaj** [comment]
Please ignore my last comment! I will merge this into `main` and cherry-pick into `web-api-6.x` myself.

**Review by filmaj — APPROVED** [review]

**Pull request merged**
