### PR TITLE
`MessageEvent` incorrectly references the Node global MessageEvent type. #2020

### LINKED ISSUE #2020: `MessageEvent` incorrectly references the Node global MessageEvent type.
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### Reproducible in:

package version: 2.13.0

node version: v20.12.1 (or higher)
 
OS version(s): Win 11

#### Steps to reproduce:

1. Install the 2.13.0 package.
2. Import any Type that uses the `MessageEvent` type.
3. Show `Property 'attachments' does not exist on type 'MessageEvent<any>'.ts(2339)` error.

#### Expected result:

No errors should occur.

#### Actual result:

`MessageEvent` should actually read `export type MessageEvent = AllMessageEvents;` but instead it references the Node global MessageEvent type.

#### Attachments:

image

I create PR later

### PR DESCRIPTION
**Pull request by varmil**
### Summary

This pull request resolves #2020 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by seratch** [comment]
@varmil Could you sign your CLA (see the above bot message)? Without that, we are unable to accept any external contributions 🙇

**Comment by varmil** [comment]
Thank you for your prompt confirmation. I have completed the CLA. Is this okay?

**Comment by seratch** [comment]
Yes, good to go! Other members in my team will be checking this PR soon. Thanks again for taking the time to fix this!

**Comment by filmaj** [comment]
Took me a bit to understand why this solution works, but it seems like references to `MessageEvent` inside `message.ts` refer to the built-in node `MessageEvent` interface and not the Slack one:

Screenshot 2024-09-10 at 11 06 11 AM

I will look to add a type test in a follow-up PR to catch this. Thank you!

**Pull request merged**
