### PR TITLE
Bump lerna dependency

### PR DESCRIPTION
**Pull request by srajiang**
###  Summary

~~Lerna is officially [not actively maintained](https://github.com/lerna/lerna/pull/3092), and as far as I can tell it isn't used at the individual package level - each package maintains it's own tests.~~

Lerna ownership was handed over to a corp sponsor! I've bumped the version. 

This change ~~removes~~ bumps this dependency. 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by misscoded — APPROVED** [review]
LGTM :shipit: The only note historically that prevented this from occurring sooner (that I could find) was [this](https://github.com/slackapi/node-slack-sdk/pull/1265#discussion_r649590219). 

So, should be good to go if that's a non-issue!

**Comment by srajiang** [comment]
@misscoded! Good call out - on further investigation, looks like lerna active maintenance got handed over to an official corporate sponsor, and they do have a recent version out, whoops. I've changed up the PR to bump the dependency instead. If that sounds good to you, I will merge.

**Comment by misscoded** [comment]
Sounds fine to me but why keep it around if we're not using it? Did it in fact cause issues with the CI/CD stuff?

**Comment by srajiang** [comment]
Spot on - so based o[n the CI/CD summary](https://github.com/slackapi/node-slack-sdk/runs/8238899663?check_suite_focus=true), we are using it to build all the packages and run some tests (I am not sure if it runs all tests of each package though) for CI/CD only. Keeping that around seems like a good thing.

**Pull request merged**
