### PR TITLE
Fix #951 TypeScript build failure related to EventEmitter types

### LINKED ISSUE #951: TypeScript build failure related to EventEmitter types
### Description

New builds on Travis are currently failing (since 8 days ago) with the following errors:

```
src/adapter.ts:16:40 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.
16 export class SlackEventAdapter extends EventEmitter {
                                          ~~~~~~~~~~~~
src/http-handler.ts:115:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
115         adapter.emit('error', error, respond);
                    ~~~~
src/http-handler.ts:117:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
117         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:121:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
121         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:202:19 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
202           adapter.emit(body.event.type, ...emitArguments);
                      ~~~~
Found 5 errors.
```

There seems to be an issue with the type definitions for `eventemitter3`.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### PR DESCRIPTION
**Pull request by seratch**
###  Summary

This pull request fixes #951 that causes the CI build failures with the `master` branch and all pull requests. Refer to the link @aoberoi shared https://github.com/slackapi/node-slack-sdk/issues/951#issuecomment-580001914 to know the cause.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by stevengill** [comment]
Looks like all of our tests are passing with this! Great!

@seratch do you know if this would this cause any issues for people using older versions of node (that we still support) ?

**Comment by seratch** [comment]
@stevengill 
Good point! We're saying as below in the document.

>This package supports Node v8 LTS and higher. It’s highly recommended to use the latest LTS version of node, and the documentation is written using syntax and features from that version.

My idea is adding a sentence like **One exception is if you use `@slack/events-api` in TypeScript, we recommend use Node v13.15 and higher since a type definition the package depends on has a backward-incompatible change since v13.15** to the **Requirements** part.

What do you think?

**Comment by stevengill** [comment]
hmm, I think requiring typescript devs to use `node >= v13.15` isn't a good idea. With node, odd numbers (like 13) are considered experimental. Most people don't use odd numbers for production.

Could we solve this tests failing problem by pinning `@types/node < 13`?

**Comment by seratch** [comment]
@stevengill Fair enough. I totally agree your idea is the best for the case (we may need to revisit the fixed version in the future though). I've modified this PR and squashed the commits into one. Once the build passes, I think this PR is ready to merge.

**Pull request merged**
