### PR TITLE
Add `author_subname` type

### PR DESCRIPTION
**Pull request by mztnnrt**
Hello! I would like to start by expressing my sincere appreciation for your consistent contributions to this project. 
Thank you so much! 

###  Summary

Add `author_subname` for message,  the section indicated by the arrow.

スクリーンショット 2023-05-05 19 03 22

---

Other language API Client  ex. [slack-go/slack](https://github.com/slack-go/slack) 

https://github.com/slack-go/slack/blob/c4095cb17cf21c2b2b9c459d5512d14ca5143f64/attachments.go#L70-L71

```go
AuthorName    string `json:"author_name,omitempty"`
AuthorSubname string `json:"author_subname,omitempty"`
```

---

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by mwbrooks** [comment]
Hey @mztnnrt 👋🏻 

Thanks a bunch for the pull request 🙇🏻 It's wonderful to hear that you've finding the project helpful and we always appreciate pull requests that continue to improve the project for everyone!

I'll be honest, I didn't know the `author_subname` property existed! Digging a little deeper, it appears to be a legacy property for message attachments. It's [not documented on api.slack.com](https://www.google.com/search?q=site%3Aapi.slack.com+%22author_subname%22), which is probably why we have not added the type definition to the SDK.

Regardless, for those in-the-know, the property is still supported by message attachments and displays correctly in Slack. It's quite slick!
image

How do the other maintainer's feel about adding this type? It seems good to me.

**Comment by mztnnrt** [comment]
Hi @mwbrooks, Thanks your reply ! 🙏

> It's [not documented on api.slack.com](https://www.google.com/search?q=site%3Aapi.slack.com+%22author_subname%22),

Yes ! In fact, I also don't know how long Slack will support `author_subname`, but now I think it useful for display_id and so on.
Therefore, i also feel good to add it. I think it is good to consider it positively.

**Comment by seratch** [comment]
@mwbrooks 
>How do the other maintainer's feel about adding this type? It seems good to me.

I also think this is a good addition 👍  We may want to add the field [here](https://api.slack.com/reference/messaging/attachments#legacy_fields) too, but missing it there at this moment doesn't necessarily prevent us from adding the actually working thing to the SDKs.

I can work on Node/Java SDKs later on.

**Comment by seratch** [comment]
My updates on this:
* Java SDK already has it: https://github.com/slackapi/java-slack-sdk/blob/v1.29.2/slack-api-model/src/main/java/com/slack/api/model/Attachment.java#L81-L82
* PR to the Python SDK: https://github.com/slackapi/python-slack-sdk/pull/1366

**Comment by mztnnrt** [comment]
Hi @seratch 👋  Thanks for your adjustment about this `subname`! 
Please continue your support 🙏

<sup>P.S. I always read your article qiita.com about Slack and it's very useful, thanks.</sup>

**Review by seratch — APPROVED** [review]

**Pull request merged**
