### PR TITLE
add getDMByUserId in data store

### PR DESCRIPTION
**Pull request by christophehurpeau**
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
- [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
- [x] I've written tests to cover the new code and functionality included in this PR.
- [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).
#### PR Summary

> New Feature: add getDMByUserId in data store

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
@christophehurpeau Looks like you need to merge `master` into your PR. Can you do that? Everything else looks good to me.

**Comment by christophehurpeau** [comment]
@DEGoodmanWilson rebased. thanks :)

**Comment by DEGoodmanWilson** [comment]
Well, this should have gone out in today's release, but it didn't and I apologize. I'll get this out next week!

**Comment by denouche** [comment]
Any news about the release of this feature?
Thanks in advance!

**Comment by christophehurpeau** [comment]
Hello @DEGoodmanWilson ! You said next week 12 days ago ?

**Comment by DEGoodmanWilson** [comment]
Well, 💩 can you rebase on master? I'm working to close out issues on Thursdays (last Thursday was Thanksgiving, something I failed to take account of), and I seriously do, honestly earnestly want to get this out today.

**Comment by christophehurpeau** [comment]
@DEGoodmanWilson rebased

**Comment by DEGoodmanWilson** [comment]
@christophehurpeau _sigh_ I'm so sorry. One more time, it looks like?

**Comment by denouche** [comment]
Please this time don't postpone this feature of 1 more week. I really need this feature. I can rebase the branch for you if you want.

**Comment by christophehurpeau** [comment]
@DEGoodmanWilson rebased

**Comment by DEGoodmanWilson** [comment]
@denouche Check out v3.7.0 ;)

**Pull request merged**
