### PR TITLE
add doclets.io config

### PR DESCRIPTION
**Pull request by lipp**
Adds documentation to [doclets.io](https://doclets.io) service. Future tags and master branch will be published automatically.

[Preview generated with my account](https://doclets.io/lipp/node-slack-client/add-to-doclets)

@grantmd / @l12s   If you like this, you are very welcomed to login to https://doclets.io with GitHub OAuth. It's 100% free for open source.
If you don't like it, I'd be happy to hear what you don't like about it :)

Steps required (3min):
1) @grantmd  / @l12s   logs in to doclets.io
2) @grantmd / @l12s   adds node-slack-client
3) someone merges this PR

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
Very interesting. Just updating this to let you know that as I build out better documentation for this project, that I'll be considering this. Thank you!

**Comment by lipp** [comment]
@DEGoodmanWilson Great! Thanks for keeping me updated! Cheers

**Comment by DEGoodmanWilson** [comment]
@lipp Now that the new documentation is out, I'm guessing you'll need to update this PR to reflect the new reality? Could you consider reworking and resubmitting?

**Comment by DEGoodmanWilson** [comment]
Specifically, I guess I mean: `CHANGELOG.md` isn't really the changelog anymore. The real changelog is now an RSS feed…how does that affect things?

**Pull request closed without merging**
