### PR TITLE
Fix broken url caused by typo

### PR DESCRIPTION
**Pull request by saintmalik**
### Summary

Easy navigation and easy reading for others

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by mwbrooks — APPROVED** [review]
Hey @saintmalik, great catch and thanks for your first-time contribution! 🎉 

I see you've already signed the CLA 🙇🏻 so I'll merge and deploy this change shortly. But first, I'll deal with the failing test that's blocking the merge - this isn't your fault, we've recently switched our CI environment and are experiencing a few sporadic failures.

**Comment by saintmalik** [comment]
> Hey @saintmalik, great catch and thanks for your first-time contribution! 🎉
> 
> I see you've already signed the CLA 🙇🏻 so I'll merge and deploy this change shortly. But first, I'll deal with the failing test that's blocking the merge - this isn't your fault, we've recently switched our CI environment and are experiencing a few sporadic failures.

Thanks @mwbrooks, okay no problem

**Comment by mwbrooks** [comment]
@saintmalik merged and deployed! :shipit:

Thanks again for the improvement to our docs:
https://slack.dev/node-slack-sdk/web-api#handle-errors

**Comment by saintmalik** [comment]
> @saintmalik merged and deployed! :shipit:
> 
> Thanks again for the improvement to our docs:
> https://slack.dev/node-slack-sdk/web-api#handle-errors

You are welcome, am happy to contribute anyway😌😊

**Pull request merged**
