### PR TITLE
NPM Audit fix: https://github.com/advisories/GHSA-cph5-m8f7-6c5x

### PR DESCRIPTION
**Pull request by xmariopereira**
###  Summary

Hi team,

NPM audit is throwing a high severity vulnerability in node-slack-sdk and with bolt-js dependency packages.

And in the way, I made the .gitignore the same for all packages. One of the packages didn't have package-lock in it. (I don't know if it was on purpose).

I hope it helps.

https://github.com/advisories/GHSA-cph5-m8f7-6c5x

### CODE REVIEW

**Comment by seratch** [comment]
@xmariopereira We're planning to have https://github.com/slackapi/node-slack-sdk/pull/1366 for web-api package. This pull request disable some of the unit tests to upgrade the axios version. Your changes under `packages/web-api` will conflict when it's merged. Could you revert all the changes under the directory? With that, we are ready to merge your changes.

**Comment by xmariopereira** [comment]
@seratch done

**Comment by seratch** [comment]
@xmariopereira Thanks for your quick response! There are currently four commits in this PR and the last one is associated with a different email address. Would you mind squashing the commits into one with the email address for xmariopereira account?

**Comment by xmariopereira** [comment]
@seratch , something is wrong with my computer... i have "2 users" and I only have one, even doing squash, it does it twice... i am going to close this PR and open it again from a different laptop...

**Pull request closed without merging**
