### PR TITLE
Issue-268: Websocket login respects https_proxy environment variable

### LINKED ISSUE #268: Websocket connection should honor 'https_proxy' environment variable
- [Y] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [Y] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [Y] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

When we setup our `hubot-slack` behind a firewall. When starting the hubot, we set `https_proxy` environment variable. When starting up, hubot prints `Logged in as BOT of TEAMNAME`, then it silently did nothing. This is confusing.

After investigation, we found that we found that slack is able to get authenticated because it uses `https_proxy`. But after that it cannot connect to websocket because it ignored the `https_proxy` settings.

In the code, we found that although there is proxy support in [ws.js](https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/transports/ws.js), but [client.js](https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L321) simply doesn't pass proxy opts. We passed the `process.env.https_proxy` to the `wsTransport` function, then hubot works correctly.

It will be good if either `client.js` or `ws.js` could check `env.https_proxy` and use it correctly during websocket creation.

Also, during investigation we found that there is a typo in [Line 21](https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/transports/ws.js#L21) that `wsTransportOpts.proxyUrl` should be `wsTransportOpts.proxyURL` (upper case URL)
#### Reproducible in:

{project_name} version:
OS version(s): Ubuntu 14.04
Device(s):
#### Steps to reproduce:
1. generate a slack hubot `yo hubot --adapter slack`
2. start it on a machine behind firewall, that can only connect to a squid proxy. Set `https_proxy` variable
### Expected result:

> hubot logged in 
### Actual result:

> hubot cannot login after printing: `Logged in as BOT of TEAMNAME`
### Attachments:

> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

### PR DESCRIPTION
**Pull request by liuweichu**
- [Y] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [Y] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [Y] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
- [Y] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferrably).
- [ ] I've written tests to cover the new code and functionality included in this PR.
- [Y] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).
#### PR Summary

If `https_proxy` is set, slack websocket will use the proxy to connect to slack server.
This solves the issue that `hubot-slack` cannot login behind firewall.
#### Related Issues

Fixes #268
#### Test strategy

The code is running great in our production env, no test case is written though. (If test is required, please guide me how to write :octocat:

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
@aoberoi Could I convince you give this a review? I'm inclined to :+1: but I'd like your eyes on it too.

**Comment by DEGoodmanWilson** [comment]
In the meantime, @liuweichu I see that the linter is rejecting your changes. In particular, we require string literals to use single-quotes, and all lines to be terminated with semi-colons. These issues must be resolved before we can accept this PR.

I apologize that this has taken me so long to come back around to, and I am eager to get this merged in!

**Comment by liuweichu** [comment]
@DEGoodmanWilson Thanks for lintering
- Rebased on current master
- `"` -> `'`
- `;` added

**Comment by aoberoi** [comment]
Oops I missed this mention! I'll find a better way to deal with the notifications moving forward.

**Pull request merged**
