### PR TITLE
Add new `file_input` block kit element soon to be introduced.

### PR DESCRIPTION
**Pull request by filmaj**
###  Summary

In preparation for next week's launch of the new Block Kit File Input element.

### CODE REVIEW

**Review by hello-ashleyintech — APPROVED** [review]
🚀

**Review by WilliamBergamin — APPROVED** [review]
LGTM but should we include the parameter for file extensions?

**Comment by henrymingwu** [comment]
FYI let's hold off on this until 11/13 at least? Context: delayed our GA by a couple of days https://slack-pde.slack.com/archives/C0539UD5E6M/p1699467241515679?thread_ts=1699461506.812299&cid=C0539UD5E6M

**Comment by WilliamBergamin** [comment]
@filmaj there is a parameter that allows the developer to restrict the file type being sent from the user I think it is `allowed_filetypes_group: "ALL"`, but I don't think we currently support this field in the parameter definition

The JSON looks like this
```js
{
        title: "Enter a file",
        name: "image-123",
        type: Schema.types.array,
        maxItems: 1,
        description: "",
        items: {
          type: Schema.slack.types.file_id,
          allowed_filetypes_group: "ALL"
        },
      }
```
I don't think we need to include this

**Comment by filmaj** [comment]
@WilliamBergamin I believe the code snippet you shared is for OpenForm fields in the automation platform. However, the interface is a bit different for the File Input block element; see the reference doc for it here: https://api.slack.com/reference/block-kit/block-elements#file_input

**Comment by WilliamBergamin** [comment]
Ohh completely missed `filetypes` field :shipit:

**Pull request merged**
