### PR TITLE
Upgrade Axios web-api to 1.6.3

### PR DESCRIPTION
**Pull request by hello-ashleyintech**
###  Summary

Fixes issue https://github.com/slackapi/node-slack-sdk/issues/1709

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Review by helzahalim — APPROVED** [review]

**Review by seratch — APPROVED** [review]
Thanks for working on this!

**Comment by seratch** [comment]
webhook project needs the same upgrade: https://github.com/slackapi/node-slack-sdk/blob/main/packages/webhook/package.json#L45

**Comment by filmaj** [comment]
If we merge this change into `main`, then it will be released when we release the new major version (v7).

In addition, we can also merge/cherry-pick into the `web-api-6.x` branch and release as a patch release for the 6.x version series.

**Review by filmaj — APPROVED** [review]

**Comment by filmaj** [comment]
I will cherry-pick this into `web-api-6.x` and do a 6.x release shortly with this fix as well.

**Pull request merged**
