### PR TITLE
Add 'style' to Button type

### PR DESCRIPTION
**Pull request by deremer**
https://api.slack.com/docs/message-guidelines

###  Summary

Add style to Button type to allow setting as 'default', 'primary', or 'danger'

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by shanedewael** [comment]
@deremer Good catch adding the button styles. 🙌 

One small thing - the docs you referenced are for the old message buttons. The newer (Block Kit) button element's `style` doesn't include `default` (only `primary` and `danger`). Would you mind making that change?

**Comment by deremer** [comment]
Ah, yes actually I had a hard time finding a good page with the actual reference, and that link was the best I could find. “Block kit” is the key to that search query. It should be this: https://api.slack.com/reference/messaging/block-elements#button

**Comment by deremer** [comment]
I will update using the Block Kit Docs when I get a moment later. Thanks.

**Comment by deremer** [comment]
@shanedewael I removed `default`

**Comment by deremer** [comment]
Any idea when this will make it into a release?

**Comment by clavin** [comment]
Sorry for the drop in communication 😬

I'm seeing if I can manage to release later today, so this will make its way into a release very soon! (Watch out for your @ in the changelog 😉)

**Comment by deremer** [comment]
Thanks!

**Pull request merged**
